
package com.mycompany.proyectoreque;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Julio David
 */
public class registerPassword extends javax.swing.JPanel {

    /**
     * Creates new form password
     */
    public registerPassword(String email) {
        initComponents();
        lblEmail.setText(email);
    }
    
     public boolean validarContraseña(String password) {
      
        String userPassword = "1234";
        
        // Si está vacío
        if (password.isEmpty()) {
            lblForgot.setText("Enter your password");
            lblForgot.setForeground(Color.RED);
            return false;
        }

        
        if (!password.equals(userPassword)) {
            lblForgot.setText("Invalid password");
            lblForgot.setForeground(Color.RED);
            return false;
        }
        
        // Si es válido, limpiar el mensaje de error
        lblForgot.setText("I forgot my password");
        lblForgot.setForeground(Color.BLACK);
        return true;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNext = new javax.swing.JButton();
        lblForgot = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblEnterPassword = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNext.setBackground(new java.awt.Color(0, 51, 255));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Create");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 117, -1));

        lblForgot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblForgot.setText("Confirm password");
        lblForgot.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblForgotFocusGained(evt);
            }
        });
        add(lblForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("email");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 330, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setText("Confirm password");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 282, 30));

        lblEnterPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEnterPassword.setText("Enter password");
        add(lblEnterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblLogo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(30, 140, 200));
        lblLogo.setIcon(new javax.swing.ImageIcon("D:\\chava\\Documents\\NetBeansProjects\\proyectoReque\\images\\logotipo.png")); // NOI18N
        lblLogo.setText("Medict");
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 26, -1, -1));

        txtPassword1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword1.setText("Password");
        txtPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword1ActionPerformed(evt);
            }
        });
        add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 282, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String password = txtPassword.getText().trim();
        boolean valido = validarContraseña(password);
        if (valido == true){
            ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        String[] args = null;
        homeMenu.main(args);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void lblForgotFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblForgotFocusGained
        lblForgot.setText("I forgot my password");
        lblForgot.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblForgotFocusGained

    private void txtPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnterPassword;
    private javax.swing.JLabel lblForgot;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword1;
    // End of variables declaration//GEN-END:variables
}
