
package com.mycompany.proyectoreque;

import java.awt.Color;

/**
 *
 * @author chava
 */
public class horasFrame extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     * @param dia
     */
    public horasFrame(String dia) {
        initComponents();
        updateTable(dia);
    }
    
    private void updateTable(String day) {
        int dia = Integer.parseInt(day);
        String presenteS = String.valueOf(dia);
        lblPresent.setText(presenteS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_730 = new javax.swing.JPanel();
        lbl730 = new javax.swing.JLabel();
        panel_900 = new javax.swing.JPanel();
        lbl900 = new javax.swing.JLabel();
        panel_1030 = new javax.swing.JPanel();
        lbl1030 = new javax.swing.JLabel();
        panel_1330 = new javax.swing.JPanel();
        lbl1330 = new javax.swing.JLabel();
        panel_1500 = new javax.swing.JPanel();
        lbl1500 = new javax.swing.JLabel();
        panel_1630 = new javax.swing.JPanel();
        lbl1630 = new javax.swing.JLabel();
        panelPresent = new javax.swing.JPanel();
        lblPresent = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panel_730.setBackground(new java.awt.Color(204, 204, 204));

        lbl730.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl730.setText("7:30 - 8:30");
        lbl730.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl730MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_730Layout = new javax.swing.GroupLayout(panel_730);
        panel_730.setLayout(panel_730Layout);
        panel_730Layout.setHorizontalGroup(
            panel_730Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl730, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_730Layout.setVerticalGroup(
            panel_730Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl730, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_900.setBackground(new java.awt.Color(241, 241, 241));

        lbl900.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl900.setText("9:00 - 10:00");
        lbl900.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl900MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_900Layout = new javax.swing.GroupLayout(panel_900);
        panel_900.setLayout(panel_900Layout);
        panel_900Layout.setHorizontalGroup(
            panel_900Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl900, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_900Layout.setVerticalGroup(
            panel_900Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl900, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panel_1030.setBackground(new java.awt.Color(204, 204, 204));

        lbl1030.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1030.setText("10:30 - 11:30");
        lbl1030.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1030MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_1030Layout = new javax.swing.GroupLayout(panel_1030);
        panel_1030.setLayout(panel_1030Layout);
        panel_1030Layout.setHorizontalGroup(
            panel_1030Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1030, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_1030Layout.setVerticalGroup(
            panel_1030Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1030, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panel_1330.setBackground(new java.awt.Color(241, 241, 241));

        lbl1330.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1330.setText("13:30 - 14:30");
        lbl1330.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1330MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_1330Layout = new javax.swing.GroupLayout(panel_1330);
        panel_1330.setLayout(panel_1330Layout);
        panel_1330Layout.setHorizontalGroup(
            panel_1330Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1330, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_1330Layout.setVerticalGroup(
            panel_1330Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1330, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panel_1500.setBackground(new java.awt.Color(204, 204, 204));

        lbl1500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1500.setText("15:00 - 16:00");
        lbl1500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1500MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_1500Layout = new javax.swing.GroupLayout(panel_1500);
        panel_1500.setLayout(panel_1500Layout);
        panel_1500Layout.setHorizontalGroup(
            panel_1500Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_1500Layout.setVerticalGroup(
            panel_1500Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1500, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panel_1630.setBackground(new java.awt.Color(241, 241, 241));

        lbl1630.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1630.setText("16:30 - 17:30");
        lbl1630.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1630MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_1630Layout = new javax.swing.GroupLayout(panel_1630);
        panel_1630.setLayout(panel_1630Layout);
        panel_1630Layout.setHorizontalGroup(
            panel_1630Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1630, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        panel_1630Layout.setVerticalGroup(
            panel_1630Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1630, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelPresent.setBackground(new java.awt.Color(204, 204, 255));

        lblPresent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPresent.setForeground(new java.awt.Color(30, 140, 200));
        lblPresent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPresent.setText("14");
        lblPresent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPresentLayout = new javax.swing.GroupLayout(panelPresent);
        panelPresent.setLayout(panelPresentLayout);
        panelPresentLayout.setHorizontalGroup(
            panelPresentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPresentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPresent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPresentLayout.setVerticalGroup(
            panelPresentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPresent, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_1630, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_1500, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_1030, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_900, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_730, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_1330, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPresent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPresent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panel_730, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_900, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_1030, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_1330, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_1500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_1630, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbl730MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl730MouseClicked
        colorChooser(0);
    }//GEN-LAST:event_lbl730MouseClicked

    private void lbl900MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl900MouseClicked
        colorChooser(1);
    }//GEN-LAST:event_lbl900MouseClicked

    private void lbl1030MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1030MouseClicked
        colorChooser(2);
    }//GEN-LAST:event_lbl1030MouseClicked

    private void lbl1330MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1330MouseClicked
        colorChooser(3);
    }//GEN-LAST:event_lbl1330MouseClicked

    private void lbl1500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1500MouseClicked
        colorChooser(4);
    }//GEN-LAST:event_lbl1500MouseClicked

    private void lbl1630MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1630MouseClicked
        colorChooser(5);
    }//GEN-LAST:event_lbl1630MouseClicked

    private void colorChooser(int index) {
        Color blue = new Color(106, 143, 173);
        Color lightGray = new Color(241, 241, 241);
        Color darkGray = new Color(204, 204, 204);
        panel_730.setBackground(darkGray);
        panel_900.setBackground(lightGray);
        panel_1030.setBackground(darkGray);
        panel_1330.setBackground(lightGray);
        panel_1500.setBackground(darkGray);
        panel_1630.setBackground(lightGray);
        switch (index) {
            case 0 -> {
                panel_730.setBackground(blue);
            }
            case 1 -> {
                panel_900.setBackground(blue);
            }
            case 2 -> {
                panel_1030.setBackground(blue);
            }
            case 3 -> {
                panel_1330.setBackground(blue);
            }
            case 4 -> {
                panel_1500.setBackground(blue);
            }
            case 5 -> {
                panel_1630.setBackground(blue);
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl1030;
    private javax.swing.JLabel lbl1330;
    private javax.swing.JLabel lbl1500;
    private javax.swing.JLabel lbl1630;
    private javax.swing.JLabel lbl730;
    private javax.swing.JLabel lbl900;
    private javax.swing.JLabel lblPresent;
    private javax.swing.JPanel panelPresent;
    private javax.swing.JPanel panel_1030;
    private javax.swing.JPanel panel_1330;
    private javax.swing.JPanel panel_1500;
    private javax.swing.JPanel panel_1630;
    private javax.swing.JPanel panel_730;
    private javax.swing.JPanel panel_900;
    // End of variables declaration//GEN-END:variables
}
